# Generated by Django 4.1.5 on 2023-01-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyCatalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
