# Generated by Django 4.1.5 on 2023-01-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyCatalogue', '0002_alter_city_options_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ManyToManyField(related_name='city', to='CompanyCatalogue.city'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='CompanyCatalogue.company'),
        ),
    ]
